// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzxrsvofiyxlfvfmtqyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eHJzdm9maXl4bGZ2Zm10cXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDEwMTgsImV4cCI6MjA2NDE3NzAxOH0.KPHE482vFlTIAq-vx_lC__DRmWhlFfMRXGy0NF37MP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);